language: python
python:
  - '3.6'
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install nose
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - dredd
script:
  - nosetests -v --with-coverage --cover-package=api
after_success:
  - coveralls
before_install:
  - npm install -g dredd@5.1.11
