FORMAT: 1A
HOST: https://mydiarry.herokuapp.com/

# MyDiary
MyDiary is an online journal where users can pen down their thoughts and feelings.
EndPoint | Functionality
------------ | -------------
POST /api/v1/auth/signup|Creates new user
POST //api/v1/auth/login|Sings in a new user
GET /entries | Fetch all entries
GET /entries/<entryId>|Fetch a single entry
POST /entries|Create an entry
PUT /entries/<entryId>|Modify an entry


## Diary Create New User Collection [/api/v1/auth/signup]


### Create a New User [POST]

Users can create an account using his email, password, phone number
This username and password is later used for loging in into the applucation

+ Request (application/json)

        {
            "name": "andella",
            "email": "andella@gmail.com",
            "username": "andella",
            "phone_number": "0708500001",
            "bio": "Great learner",
            "gender": "Male",
            "password": "moschinogab19"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/v1/auth/signup

    + Body

            {
                "message": "Account successfully created"
            }
            


## Diary User Login Collection [/api/v1/auth/login]
### Login User [POST]

By using the username and password created in create new user
Aperson should be able to generate a token when all his creditials meet the expectiations

+ Request (application/json)

        {
            "username": "andella",
            "password": "moschinogab19"
        }

+ Response 200 (application/json)

    + Headers

            Location: /auth/login

    + Body

            {
                "Message": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiZXhwIjoxNTMzMjA3MzkyfQ.ACuyqxBpGbZ3JbMwS3vmOmX4YPT0kEFvZmPHhOvsm7w"
            }
            
## Diary Creation Collection [/api/v1/auth/entries]
### Create Entry [POST]

By using the token on the header, a user is able to post in his or her new entries in to his diary.
He can later access the same 

+ Request (application/json)

        {
            "title": "Wawww",
            "body": "When things are tricky you cool down"
        }
        
+ Response 201 (application/json)

    + Headers

            Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiZXhwIjoxNTMzMjA3MzkyfQ.ACuyqxBpGbZ3JbMwS3vmOmX4YPT0kEFvZmPHhOvsm7w
            
            

    + Body

            {
                "message": "Entry created successfully"
            }
            

## Diary Collection [/api/v1/entries]
### List All Entries [GET]
A user can get all the list of all entries he or she has created


+ Response 200 (application/json)

        [
            {
                "Entries": [
                    {
                        "body": "When things are tricky you cool down",
                        "creation_date": "2018-08-02",
                        "entry_id": 1,
                        "title": "Wawww",
                        "update_date": null
                    }
                ]
            }
        ]
        
## Diary Get Entry By ID Collection [/api/v1/entries/1]
### List Entries By Entry ID [GET]
A user can get an entry by entry id  he or she has created

+ Response 200 (application/json)

        [
            {
                "body": "When things are tricky you cool down",
                "creation_date": "2018-08-02",
                "title": "Wawww",
                "update_date": null
            }
        ]
        
## Diary Entry Update Collection [/api/v1/entries/2]
### Update Entry By Id [PUT]
Using the entry ID the user is able to update and entry and this should only the
body and title
+ Request (application/json)

        {
            "title": "andella",
            "body": "moschinogab19"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/v1/entries/2

    + Body

            {
                "message": "Entry with id 1 updated successfully"
            }